# Dimensionality-reduction PCA Manual

In [99]:
import pandas as pd
import numpy as np
#use widget instead of inline to make the plot interactive
%matplotlib inline 
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
# plt.rcParams['figure.figsize'] = [18, 11]
# font = {'size'   : 22}

plt.rc('font', **font)
# plt.rcParams['figure.figsize'] = [15, 10]
ht_grouped = pd.read_csv('data/ht_grouped_feature_engineered.csv',index_col='device_id')
# https://towardsdatascience.com/a-complete-guide-to-principal-component-analysis-pca-in-machine-learning-664f34fc3e5a

In [100]:
ht_grouped.head()

resting_heartrate_avg  \
device_id                                                     
0003a6b8-e48b-11ea-8204-0242ac110002              82.683797   
0007a88a-e48b-11ea-8204-0242ac110002              77.732942   
000b9c56-e48b-11ea-8204-0242ac110002              86.511629   
000f916c-e48b-11ea-8204-0242ac110002              77.550541   
00176e5a-e48b-11ea-8204-0242ac110002              69.312448   

                                      resting_heartrate_min  \
device_id                                                     
0003a6b8-e48b-11ea-8204-0242ac110002              60.677755   
0007a88a-e48b-11ea-8204-0242ac110002              52.712876   
000b9c56-e48b-11ea-8204-0242ac110002              63.903506   
000f916c-e48b-11ea-8204-0242ac110002              58.418806   
00176e5a-e48b-11ea-8204-0242ac110002              47.355699   

                                      resting_heartrate_max  \
device_id                                                     
0003a6b8-e48b-11ea-8204-0242ac110002             100.121903   
0007a88a-e48b-11ea-8204-0242ac110002              97.937731   
000b9c56-e48b-11ea-8204-0242ac110002             104.437895   
000f916c-e48b-11ea-8204-0242ac110002              98.875329   
00176e5a-e48b-11ea-8204-0242ac110002              92.762496   

                                      active_heartrate_avg  \
device_id                                                    
0003a6b8-e48b-11ea-8204-0242ac110002            139.434875   
0007a88a-e48b-11ea-8204-0242ac110002            127.057153   
000b9c56-e48b-11ea-8204-0242ac110002            147.315731   
000f916c-e48b-11ea-8204-0242ac110002            129.577004   
00176e5a-e48b-11ea-8204-0242ac110002            167.185850   

                                      active_heartrate_min  \
device_id                                                    
0003a6b8-e48b-11ea-8204-0242ac110002            120.307791   
0007a88a-e48b-11ea-8204-0242ac110002            109.049387   
000b9c56-e48b-11ea-8204-0242ac110002            129.551728   
000f916c-e48b-11ea-8204-0242ac110002            110.845517   
00176e5a-e48b-11ea-8204-0242ac110002            147.876166   

                                      active_heartrate_max    bmi_avg  \
device_id                                                               
0003a6b8-e48b-11ea-8204-0242ac110002            162.347827  22.398064   
0007a88a-e48b-11ea-8204-0242ac110002            146.869868  25.150813   
000b9c56-e48b-11ea-8204-0242ac110002            177.783150  19.148256   
000f916c-e48b-11ea-8204-0242ac110002            146.738650  24.240376   
00176e5a-e48b-11ea-8204-0242ac110002            186.283615  27.132669   

                                        bmi_min    bmi_max    vo2_avg  \
device_id                                                               
0003a6b8-e48b-11ea-8204-0242ac110002  19.530816  24.997081  20.994012   
0007a88a-e48b-11ea-8204-0242ac110002  22.635269  27.933614  25.527475   
000b9c56-e48b-11ea-8204-0242ac110002  16.844741  21.339665  19.448407   
000f916c-e48b-11ea-8204-0242ac110002  21.335820  26.909150  21.401302   
00176e5a-e48b-11ea-8204-0242ac110002  23.589288  31.026467  30.939205   

                                        vo2_min    vo2_max  \
device_id                                                    
0003a6b8-e48b-11ea-8204-0242ac110002  20.283341  21.491176   
0007a88a-e48b-11ea-8204-0242ac110002  24.929151  26.231702   
000b9c56-e48b-11ea-8204-0242ac110002  18.817131  19.946847   
000f916c-e48b-11ea-8204-0242ac110002  20.705860  22.088526   
00176e5a-e48b-11ea-8204-0242ac110002  30.032978  32.026828   

                                      workout_minutes_avg  \
device_id                                                   
0003a6b8-e48b-11ea-8204-0242ac110002             5.502632   
0007a88a-e48b-11ea-8204-0242ac110002            37.216702   
000b9c56-e48b-11ea-8204-0242ac110002            45.000087   
000f916c-e48b-11ea-8204-0242ac110002            37.886069   
00176e5a-e48b-11e

In [101]:
feature_len = ht_grouped.drop('lifestyle',axis=1).columns.values.__len__()

In [102]:
X = ht_grouped.drop('lifestyle',axis=1).values
y = ht_grouped.lifestyle.values

In [103]:
from sklearn.preprocessing import StandardScaler 
X_std = StandardScaler().fit_transform(X)

In [104]:
#mean_vec = np.mean(X_std, axis=0) 
#cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1) 
#print('Covariance matrix \n%s' %cov_mat) 
print('Covariance matrix \n') 
cov_mat= np.cov(X_std, rowvar=False) 
cov_mat

Covariance matrix 



array([[ 1.0003651 ,  0.97949214,  0.97920131,  0.80404941,  0.7960349 ,
         0.79490244,  0.14698909,  0.14591633,  0.14712347, -0.94187662,
        -0.94173104, -0.94184925, -0.38131979,  0.53924719, -0.51486292,
        -0.78989463, -0.62044704, -0.77849016,  0.13673787],
       [ 0.97949214,  1.0003651 ,  0.95646753,  0.78735425,  0.77939431,
         0.77831369,  0.14513807,  0.14412768,  0.1450995 , -0.9203176 ,
        -0.92015495, -0.92029986, -0.37856903,  0.52441213, -0.50917039,
        -0.772487  , -0.6036799 , -0.76215408,  0.13410617],
       [ 0.97920131,  0.95646753,  1.0003651 ,  0.78996204,  0.7811754 ,
         0.78190025,  0.14437818,  0.14369897,  0.14414706, -0.92027164,
        -0.92022848, -0.92020592, -0.37360017,  0.52648072, -0.5021054 ,
        -0.77344653, -0.61052122, -0.76171538,  0.13145043],
       [ 0.80404941,  0.78735425,  0.78996204,  1.0003651 ,  0.98871608,
         0.98860062,  0.33516197,  0.33349989,  0.33424522, -0.78598967,
        -0.785

In [105]:
cov_mat = np.cov(X_std.T) 
eig_vals, eig_vecs = np.linalg.eig(cov_mat) 
print('Eigenvectors \n%s' %eig_vecs) 
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-2.73775835e-01  1.56386235e-01 -3.46366527e-03 -1.44567599e-01
   1.51665436e-01  4.35761372e-02  2.50047005e-01  1.63878167e-01
   1.91758330e-01  5.06354434e-03 -2.39613083e-03 -3.16969481e-02
  -3.12822045e-02 -8.52287821e-01 -1.24848628e-02  7.12612358e-03
   3.11183693e-03  8.54351845e-04 -4.96564086e-15]
 [-2.68903157e-01  1.53616663e-01  1.81272208e-03 -1.51259298e-01
   1.58056053e-01  3.65314746e-02  3.21302281e-01  2.12703057e-01
   2.63638348e-01  6.98969192e-01 -1.06988917e-01  4.35456702e-02
   2.58911793e-02  3.66466507e-01  6.09229062e-03 -2.23661924e-03
   4.50699419e-04  3.74739985e-05  4.59027007e-16]
 [-2.69026902e-01  1.54651544e-01 -3.40329012e-03 -1.46716942e-01
   1.47659251e-01  4.82889550e-02  3.14577939e-01  2.07916272e-01
   2.92116582e-01 -6.87308970e-01  1.61970362e-01 -2.20370385e-02
   6.13233064e-03  3.62398441e-01  4.50698348e-03 -1.97068785e-03
  -2.46232487e-03 -4.55105154e-04  2.90700959e-15]
 [-2.71919056e-01  2.79048921e-02 -5.1211

In [106]:
sq_eig=[] 
for i in eig_vecs: 
    sq_eig.append(i**2) 
    print(sq_eig) 
sum(sq_eig) 
print("sum of squares of each values in an eigen vector is \n", 2.23466464e-01+ 1.54732629e-02+ 2.03004679e-05+ 5.12992101e-01+ 7.13026850e-03+ 8.52287437e-02+ 1.24049769e-01+ 1.09474404e-04+3.07172181e-02+ 6.10117336e-04+ 2.02280577e-04) 
for ev in eig_vecs: np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev),decimal=3)

[array([7.49532078e-02, 2.44566546e-02, 1.19969771e-05, 2.08997906e-02,
       2.30024045e-02, 1.89887973e-03, 6.25235049e-02, 2.68560535e-02,
       3.67712570e-02, 2.56394813e-05, 5.74144294e-06, 1.00469652e-03,
       9.78576316e-04, 7.26394530e-01, 1.55871799e-04, 5.07816373e-05,
       9.68352910e-06, 7.29917075e-07, 2.46575892e-29])]
[array([7.49532078e-02, 2.44566546e-02, 1.19969771e-05, 2.08997906e-02,
       2.30024045e-02, 1.89887973e-03, 6.25235049e-02, 2.68560535e-02,
       3.67712570e-02, 2.56394813e-05, 5.74144294e-06, 1.00469652e-03,
       9.78576316e-04, 7.26394530e-01, 1.55871799e-04, 5.07816373e-05,
       9.68352910e-06, 7.29917075e-07, 2.46575892e-29]), array([7.23089080e-02, 2.35980792e-02, 3.28596135e-06, 2.28793752e-02,
       2.49817160e-02, 1.33454864e-03, 1.03235156e-01, 4.52425905e-02,
       6.95051783e-02, 4.88557932e-01, 1.14466283e-02, 1.89622539e-03,
       6.70353165e-04, 1.34297701e-01, 3.71160050e-05, 5.00246563e-06,
       2.03129967e-07, 1.4043005

In [107]:
#Make a list of (eigenvalue, eigenvector) tuples 
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [108]:
#Sort the (eigenvalue, eigenvector) tuples from high to low 
eig_pairs.sort() 
eig_pairs.reverse() 
# print("\n",eig_pairs) 
#Visually confirm that the list is correctly sorted by decreasing eigenvalues 
print('\n\n\nEigenvalues in descending order:') 
for i in eig_pairs: 
    print(i[0])




Eigenvalues in descending order:
11.267286483674372
3.7681455544723126
1.3830661769561994
0.8025621813269781
0.695310343665899
0.4551134682623233
0.1944915175370646
0.15473292407545947
0.1400071362986867
0.04394304159826082
0.04028463696243611
0.02411879502221342
0.016329485734426566
0.011749450937104904
0.00738511312657
0.001989536974651515
0.0003215927246138273
9.939891257997152e-05
2.120741076925885e-16


In [109]:
num_k = 5
tot = sum(eig_vals) 
print("\n",tot) 
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)] 
print("\n\n1. Variance Explained\n",var_exp) 
cum_var_exp = np.cumsum(var_exp) 
print("\n\n2. Cumulative Variance Explained\n",cum_var_exp) 
print("\n\n3. Percentage of variance the first two principal components each contain\n ",var_exp[0:num_k]) 
print("\n\n4. Percentage of variance the first two principal components together contain\n",sum(var_exp[0:num_k]))


 19.006936838262153


1. Variance Explained
 [59.27986492275083, 19.825106941413097, 7.276638990939353, 4.222469870638862, 3.658192530351318, 2.3944598339809886, 1.0232659749020736, 0.8140865905545202, 0.7366107305457215, 0.23119475785177931, 0.21194702389572112, 0.12689469759093835, 0.0859132950952638, 0.06181664640171016, 0.03885483068320249, 0.010467425611929496, 0.001691975552664757, 0.000522961240024091, 1.1157721493853235e-15]


2. Cumulative Variance Explained
 [ 59.27986492  79.10497186  86.38161086  90.60408073  94.26227326
  96.65673309  97.67999906  98.49408566  99.23069639  99.46189114
  99.67383817  99.80073287  99.88664616  99.94846281  99.98731764
  99.99778506  99.99947704 100.         100.        ]


3. Percentage of variance the first two principal components each contain
  [59.27986492275083, 19.825106941413097, 7.276638990939353, 4.222469870638862, 3.658192530351318]


4. Percentage of variance the first two principal components together contain
 94.26227325609345


In [110]:
# print(eig_pairs[0][1]) 
# print(eig_pairs[1][1])
# print(eig_pairs[2][1])
matrix_w = np.hstack((eig_pairs[0][1].reshape(feature_len,1), 
                      eig_pairs[1][1].reshape(feature_len,1),
                      eig_pairs[2][1].reshape(feature_len,1),
                      eig_pairs[3][1].reshape(feature_len,1),
                      eig_pairs[4][1].reshape(feature_len,1),
                      eig_pairs[5][1].reshape(feature_len,1),)) 
#hstack: Stacks arrays in sequence horizontally (column wise). 
print('Matrix W:\n', matrix_w)
matrix_w[0]

Matrix W:
 [[-0.27377583  0.15638624 -0.00346367 -0.1445676   0.15166544  0.04357614]
 [-0.26890316  0.15361666  0.00181272 -0.1512593   0.15805605  0.03653147]
 [-0.2690269   0.15465154 -0.00340329 -0.14671694  0.14765925  0.04828896]
 [-0.27191906  0.02790489 -0.05121136  0.00563916 -0.42641627 -0.2513042 ]
 [-0.26947562  0.0279756  -0.0588208   0.00755414 -0.43031806 -0.26350098]
 [-0.26908858  0.02915822 -0.04915099  0.00682166 -0.43708292 -0.26213217]
 [-0.12777847 -0.45276972 -0.1198753  -0.11521632  0.04508997  0.02964508]
 [-0.12695277 -0.44913164 -0.11631134 -0.11267828  0.04187089  0.02936807]
 [-0.1278723  -0.45468076 -0.12079127 -0.11827612  0.04861151  0.03110987]
 [ 0.26559667 -0.16855193  0.05753617  0.2599233  -0.13202151 -0.08986161]
 [ 0.2655522  -0.168639    0.05750151  0.25991814 -0.13211321 -0.08965019]
 [ 0.26557469 -0.16871619  0.05763452  0.25955059 -0.13170841 -0.0901001 ]
 [ 0.15282998  0.15430855 -0.67325992  0.03243855 -0.0288038   0.06191891]
 [-0.1725648  

array([-0.27377583,  0.15638624, -0.00346367, -0.1445676 ,  0.15166544,
        0.04357614])

In [111]:
Y = X_std.dot(matrix_w) 
principalDf = pd.DataFrame(data = Y , columns = ['principal component {}'.format(s+1) for s in range(len(matrix_w[0]))]) 
principalDf.head()

principal component 1  principal component 2  principal component 3  \
0              -5.430352               1.030918               2.563699   
1              -3.380611               0.349473              -0.994894   
2              -4.766143               3.511397              -1.400717   
3              -3.770084               0.969242              -1.145421   
4              -5.351944              -2.193435               1.943638   

   principal component 4  principal component 5  principal component 6  
0               0.050385              -0.177438               0.875352  
1               0.765457               1.172089               0.156962  
2              -0.161016              -0.379004              -0.838252  
3              -0.115691               1.457447              -0.201180  
4               0.839855              -2.812703              -0.957007

In [112]:
finalDf = pd.concat([principalDf,pd.DataFrame(y,columns = ['lifestyle'])], axis = 1) 
finalDf.head()

principal component 1  principal component 2  principal component 3  \
0              -5.430352               1.030918               2.563699   
1              -3.380611               0.349473              -0.994894   
2              -4.766143               3.511397              -1.400717   
3              -3.770084               0.969242              -1.145421   
4              -5.351944              -2.193435               1.943638   

   principal component 4  principal component 5  principal component 6  \
0               0.050385              -0.177438               0.875352   
1               0.765457               1.172089               0.156962   
2              -0.161016              -0.379004              -0.838252   
3              -0.115691               1.457447              -0.201180   
4               0.839855              -2.812703              -0.957007   

        lifestyle  
0       Sedentary  
1  Weight Trainer  
2  Weight Trainer  
3  Weight Trainer  
4       Sedentary

In [113]:
finalDf.to_pickle('data/dim_reduced_df.pkl')

In [114]:
fig = plt.figure(figsize = (14,8)) 
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15) 
ax.set_ylabel('Principal Component 2', fontsize = 15) 
ax.set_title('2 Component PCA', fontsize = 20) 
targets = ['Sedentary','Weight Trainer','Athlete','Cardio Enthusiast']
colors = ['r', 'g', 'b','c'] 
for target, color in zip(targets,colors): 
    indicesToKeep = finalDf['lifestyle'] == target  
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1'] , 
               finalDf.loc[indicesToKeep, 'principal component 2'] , 
               c = color , s = 50) 
ax.legend(targets) 
ax.grid()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [115]:
scatter_df = finalDf[['principal component 1', 'principal component 2','principal component 3','lifestyle']]
Sedentary = scatter_df.loc[scatter_df.lifestyle == 'Sedentary']
Trainer = scatter_df.loc[scatter_df.lifestyle == 'Weight Trainer']
Athlete = scatter_df.loc[scatter_df.lifestyle == 'Athlete']
Cardio = scatter_df.loc[scatter_df.lifestyle == 'Cardio Enthusiast']

In [116]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
df_list =    [Sedentary,Trainer,Athlete,Cardio]
color_list = ['r','b','c','m']
label_list = ['Sedendary','Weight Trainer','Athlete','Cardio Enthusiast']

for _, (df_c, color,lbl) in enumerate(zip(df_list, color_list, label_list)):
    ax.scatter(df_c['principal component 1'],df_c['principal component 2'],df_c['principal component 3'],color=color, label=lbl)

ax.set_xlabel('principal component 1')
ax.set_ylabel('principal component 2')
ax.set_zlabel('principal component 3')
plt.legend(loc='upper left', numpoints=1, ncol=3,)

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …